name: 버그 리포트
description: 문제가 발생했을 때 사용하는 템플릿

labels: [버그]

body:
  - type: textarea
    attributes:
      label: 문제 재현
      description: 문제를 재현하기 위해 어떤 상황에서, 어떤 동작을 했는지 자세하게 설명해주세요.
      placeholder: |
        1. 다음과 같이 코드 작성

        ```ts
        export const a = 1

        a = 2
        ```

        2. 다음과 같은 오류 발생

        ```
        test.ts:3:1 - error TS2588: Cannot assign to 'a' because it is a constant.

        3 a = 2
          ~


        Found 1 error in test.ts:3
        ```
