name: 자동 테스트

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.18.2, 20.9.0, 21.x]

    name: Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - run: npm ci
      - name: 포매팅
        run: npx prettier --check .
      - run: npm test
