name: 자동 테스트

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        node: [20.9.0, 21.x]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}/Node.js ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - run: npm ci

      - if: startsWith( matrix.os, 'ubuntu' )
        name: 포매팅
        run: npx prettier --check .

      # windows + node v20.9.0에서 glob이 제대로 동작하지 않음
      - if: ${{ !( startsWith( matrix.os, 'windows' ) && matrix.node == '20.9.0' ) }}
        run: npm test
